name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run Fastlane Tests
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Altere se necessário

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Fastlane Tests
        run: bundle exec fastlane test
